### ISSUE TITLE
Nested mono project path resolve failed for node esm

### ISSUE THREAD

**Issue by tianyingchun** [sleep-written/bleed-believer#1] opened 2022-12-23 04:58 UTC
e.g.

1. pakcages/
    + terminal
      + src/index.ts
      // tsconfig.json
       paths: {}
    + logger
       + src/index.ts
       // tsconfig.json
      "paths": {
          "@armit/terminal": ["../../terminal/src/index.js"]
       },
    + main
       + src/index.ts
        invoke `import { LogLevel } from '@armit/logger';`
        
        
above scenario it will throw · ERR_MODULE_NOT_FOUND·

**Comment by sleep-written** [comment] 2023-01-02 02:03
How do you launch your app in terminal?

**Comment by sleep-written** [comment] 2023-01-02 02:13
I suppose you are using `@bleed-believer/path-alias`, so I don't tested the loader in a monorepo. So at now, the package wasn't designed to launch monorepo apps. But in a future major release i'll evaluate the posibility to launch monorepo apps. For that reason, i need more info to reproduce your scenario:
- The `tsconfig.json` in the root directory of your project.
- How you launch your app in terminal.

So, you must considerate that this package has some limitations for now:
- Needs a `tsconfig.json` in the current working directory.
- If that file extends another configuration file, you must can access to all aliases through the dependency hierachy (using "extends" fields in `tsconfig.json`).

**Comment by sleep-written** [comment] 2023-02-27 11:20
Due to lack of details about the project, I'll close this issue, However, in a future i'll check if the monorepo support it's possible to be implemented in this library.

**Closed as completed by sleep-written** 2023-02-27 11:20 UTC
Labels: bug, enhancement
